-- CivicConnect initial PostgreSQL migration for Supabase

create extension if not exists pgcrypto;


-- Request categories
create table request_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true
);


-- Request statuses
create table request_statuses (
  id bigint generated by default as identity primary key,
  name text not null unique
);


-- Service requests
create table service_requests (
  id uuid primary key default gen_random_uuid(),
  reference_number text not null unique,

  category_id bigint not null
    references request_categories(id),

  title varchar(120) not null,
  description text not null,

  status_id bigint not null
    references request_statuses(id),

  requester_id uuid
    references auth.users(id),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint service_request_title_not_blank
    check (length(trim(title)) > 0),

  constraint service_request_description_not_blank
    check (length(trim(description)) > 0)
);


-- Status history
create table request_status_history (
  id bigint generated by default as identity primary key,

  request_id uuid not null
    references service_requests(id)
    on delete cascade,

  status_id bigint not null
    references request_statuses(id),

  changed_at timestamptz not null default now()
);


-- Helpful indexes
create index idx_service_requests_requester
  on service_requests(requester_id);

create index idx_service_requests_status
  on service_requests(status_id);


-- Initial request statuses
insert into request_statuses (name)
values
  ('Submitted'),
  ('In Progress'),
  ('Resolved'),
  ('Closed');


-- Enable Row Level Security
alter table service_requests
  enable row level security;

alter table request_status_history
  enable row level security;